source: https://github.com/gentoo-build-service/docker-images
image: gentoobuildservice/builder-docker-amd64
directory: /
script:
  - source storage/env
  - "curl -s https://api.github.com/repos/mudler/docker-companion/releases/latest | grep 'browser_download_url.*amd64' | cut -d : -f 2,3 | tr -d \\\" | wget -i - -O docker-companion; chmod a+x docker-companion"
  - docker build --no-cache -t gentoobuildservice/builder-amd64 .
  - ./docker-companion squash --remove gentoobuildservice/builder-amd64
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker push gentoobuildservice/builder-amd64
task: docker_execute
storage: '5778981929632715504'
planned: "@daily"
